[package]
name = "ftfrs-tracing"
version = "0.1.0"
edition = "2021"

[dependencies]
ftfrs = "0.1.1"
lock_api = "0.4.12"
parking_lot = { version = "0.12.3", features = ["send_guard", "serde"] }
tracing = "0.1.41"
tracing-core = "0.1.33"
tracing-subscriber = "0.3.19"

[[example]]
name = "run"
